# Site settings
author: Codi Kraus
title: CK Coding Odyssey
header-img: img/home-bg.png
email: codi.kraus@gmail.com
copyright_name: Codi Kraus
description: > # this means to ignore newlines until "baseurl:"
  Going from Lawyer to Programmer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ph3nomforko

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
